### ISSUE TITLE
Receive "undefined is not a function" Type error when processing payments using Payflow Pro

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction-paypal#28]
This appears to have been introduced in v1.2.8 as the error doesn't happen if I switch back to v1.2.7. I tried reverting just the SDK and that did not appear to help.

Steps to reproduce:

1. Place an order using Payflow Pro
2. Wait for a few moments (YMMV) 
3. See in server console you get: (no error is surfaced to the user)

```/Users/brenthoover/Projects/js/reaction/packages/reaction-paypal/.npm/package/node_modules/paypal-rest-sdk/lib/api.js:149
                cb(error, response);
                ^
TypeError: undefined is not a function
    at /Users/brenthoover/Projects/js/reaction/packages/reaction-paypal/.npm/package/node_modules/paypal-rest-sdk/lib/api.js:149:17
    at IncomingMessage.<anonymous> (/Users/brenthoover/Projects/js/reaction/packages/reaction-paypal/.npm/package/node_modules/paypal-rest-sdk/lib/client.js:146:13)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
=> Exited with code: 8
```

The nice part about this error is that it seems to go into an infinite loop even though the actual capture seems to have worked.

**Comment by zenweasel** [comment]
No longer able to replicate. Closing.
